# Generated by Django 4.1.7 on 2023-03-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0001_initial'),
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity', to='user_activity.useractivity'),
        ),
    ]
